dist: focal
env:
  global:
    - secure: jKV3Hj/lvoNjU2JUSUlLsLAHX+BI0R27+qTEPSihHpNGB+NOvbwlfpisrqxA/9nanVhtq9I3PJi2Jd5Pkg+3TkYvRq62ZT1Ty/DuxbQmMWlhEZT6wxbVS7919OZ3K0WAOizt3/HzSxL5XZheGRAKf89SoUF6mOP4V3DCh5rzze4=
  matrix:
    - TOOLCHAIN=
    - TOOLCHAIN=raspberry.toolchain
    - TOOLCHAIN=mips.toolchain
addons:
  coverity_scan:
    project:
      name: mpromonet/v4l2rtspserver
    build_command_prepend: cmake .
    build_command: make
    branch_pattern: coverage
    notification_email: scan_notifications@example.com
  apt:
    sources:
      - deadsnakes
    packages:
      - git
      - cmake 
      - libasound2-dev
      - g++-mips-linux-gnu
      - g++-aarch64-linux-gnu
before_install:
  - pip install --user cpp-coveralls pyYaml
language: cpp
compiler: gcc
script:
  - echo "TOOLCHAIN=$TOOLCHAIN"
  - if [ "$TOOLCHAIN" == "raspberry.toolchain" ]; then git clone --depth 1 https://github.com/raspberrypi/tools.git rpi_tools && export PATH=$PATH:$(pwd)/rpi_tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin ; fi
  - if [ "${TOOLCHAIN}" != "" ]; then cmake -DCMAKE_TOOLCHAIN_FILE=$(pwd)/${TOOLCHAIN} . ; else cmake . ; fi
  #build 
  - make 
  - cpack .
  #run coverage test
  - if [ "$COVERAGE" != "" ]; then cmake -DCOVERAGE=ON . && make && make test; fi
after_success:
  - if [ "$COVERAGE" != "" ]; then coveralls --gcov-options '\-lp'; fi
#before_deploy:
#  - export RELEASE_DEB_FILE=$(ls *.deb)
#deploy:
#  provider: releases
#  api_key:
#    secure: gcQy7QO09vfGtcRMi8D+6VykDfK1tuz1jEZRmJER6eZ0p2gRi4F6mtsMRJWt3QsKkZQWkJpPTvCfv9GyNmWTrZV746y5QVnd+mjPx+6K/LgroK4LWgOgzJ6zQ6qfDKU80GbxJOnNv9/HmIcxSCiactxS50tbvntqpBGCmiIL+4U=
#  file: 
#    - "${RELEASE_DEB_FILE}"
#  skip_cleanup: true
#  on:
#    repo: mpromonet/v4l2rtspserver
#    tags: true
