dist: trusty
before_install:
- sudo apt-get install -y cmake liblog4cpp5-dev liblivemedia-dev libasound2-dev
- sudo apt-get install -y qemu-user-static debootstrap 
- host mirrors.kernel.org
- sudo debootstrap --variant=minbase --arch armhf --foreign --include=g++,liblog4cpp5-dev,liblivemedia-dev,libasound2-dev jessie rootfs http://sfo-korg-mirror.kernel.org/debian
- sudo cp /usr/bin/qemu-arm-static rootfs/usr/bin/
- sudo chroot rootfs /debootstrap/debootstrap --second-stage
- git clone https://github.com/raspberrypi/tools.git rpi_tools
- export PATH=$(pwd)/rpi_tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:$PATH
- pip install --user cpp-coveralls pyYaml
language: cpp
compiler:
- gcc
script:
- cmake . && make && cpack .
- cmake -DCOVERAGE=ON . && make && make test
#- rm -rf CMakeCache.txt *.a CMakeFiles
#- cmake . -DCMAKE_TOOLCHAIN_FILE=raspberry.toolchain && make && cpack .
after_success:
- coveralls --gcov-options '\-lp'
env:
  global:
  - secure: hcQTuiLgzgWcinU2QKOlVI7xe0/XWAf6PnBbQG6YI7CkoQWMOaayime+07CpkRFM83GnZ7pc6qeA+RzVjwTZVfyIM8/T0af0mSNqop/ciflFa8t6v3k4nmUsWB9Cw9vEPdfuzsUMU1g7+qGFBMFRQj4lwgxgVll/S9wAUjD14pU=
addons:
  coverity_scan:
    project:
      name: mpromonet/h264_v4l2_rtspserver
    build_command_prepend: cmake .
    build_command: make
    branch_pattern: master
    notification_email: scan_notifications@example.com
before_deploy:
  - export RELEASE_PKG_FILE_X86=$(ls *-x86_64.deb)
  - export RELEASE_PKG_FILE_ARM=$(ls *-armhf.deb)
  - echo "deploying ${RELEASE_PKG_FILE_X86} ${RELEASE_PKG_FILE_ARM} to GitHub releases"    
deploy:
  provider: releases
  api_key:
    secure: HvPy3gyZ1nGPLAMgpRvJO2yFqpYBU7HzPQVr8LkBuOIMfya+08fbrQ9lRmvGI/3R4hwx4aPZug2DEfedP07vFXmbISLy/VTeL9TBg86CKX4vPywaoqiv5mTECUp29pmj9R3aCrIK0ROjuXQJqLN1/+jsAEnvh/gBMplQuM6a3Zc=
  file: 
    - "${RELEASE_PKG_FILE_X86}"
    - "${RELEASE_PKG_FILE_ARM}"
  skip_cleanup: true
  on:
    repo: mpromonet/h264_v4l2_rtspserver
    tags: true
