before_install: 
- sudo apt-get update
- sudo apt-get install cmake libv4l-dev liblog4cpp5-dev
- wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/libl/liblivemedia/liblivemedia-dev_2014.01.13-1_amd64.deb
- wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/libl/liblivemedia/libbasicusageenvironment0_2014.01.13-1_amd64.deb
- wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/libl/liblivemedia/libgroupsock1_2014.01.13-1_amd64.deb
- wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/libl/liblivemedia/liblivemedia23_2014.01.13-1_amd64.deb
- wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/libl/liblivemedia/libusageenvironment1_2014.01.13-1_amd64.deb
- sudo dpkg -i liblivemedia-dev_2014.01.13-1_amd64.deb libbasicusageenvironment0_2014.01.13-1_amd64.deb libgroupsock1_2014.01.13-1_amd64.deb liblivemedia23_2014.01.13-1_amd64.deb libusageenvironment1_2014.01.13-1_amd64.deb

language: cpp
compiler:
- gcc

script: 
- cmake . 
- make
- cpack .

env:
  global:
   - secure: "hcQTuiLgzgWcinU2QKOlVI7xe0/XWAf6PnBbQG6YI7CkoQWMOaayime+07CpkRFM83GnZ7pc6qeA+RzVjwTZVfyIM8/T0af0mSNqop/ciflFa8t6v3k4nmUsWB9Cw9vEPdfuzsUMU1g7+qGFBMFRQj4lwgxgVll/S9wAUjD14pU="

addons:
  coverity_scan:
    project:
      name: "mpromonet/h264_v4l2_rtspserver"
    build_command_prepend: "cmake ."
    build_command:   "make"
    branch_pattern: master
