name: ORT

on: [push]

jobs:
  build:
    strategy:
      matrix:
        buildtype: [Debug, Release]

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.1'

    - name: Analyze licensing 
      id: ort-action
      uses: edulix/ort-action@v0.1.2

    - uses: actions/upload-artifact@v2
      with:
        name: licenses
        path: ${{ steps.ort-action.outputs.results-dir }}
